### ISSUE TITLE
IOU does not start on Bionic

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1329]
After upgrading from Xenial to Bionic, IOU no longer starts. Error output:
```
=> error while starting R1: The following shared library dependencies cannot be found for IOU image /home/adosztal/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-15.4.1T.bin: libcrypto.so.4
The following shared library dependencies cannot be found for IOU image /home/adosztal/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-15.4.1T.bin: libcrypto.so.4
```
I get the same issue when trying to start the image from console:
```
adosztal@lab:~/GNS3/images/IOU$ ./i86bi-linux-l3-adventerprisek9-15.4.1T.bin 1
./i86bi-linux-l3-adventerprisek9-15.4.1T.bin: error while loading shared libraries: libcrypto.so.4: cannot open shared object file: No such file or directory
```

Note: I also tried installing gns3-iou by following the install steps in the [docs](https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html) but neither that worked out well:
```
adosztal@lab:~$ sudo dpkg --add-architecture i386

adosztal@lab:~$ sudo apt-get update
[ output omitted ]
Fetched 242 kB in 2s (109 kB/s)                     
Reading package lists... Done

adosztal@lab:~$ sudo apt-get install gns3-iou
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gns3-iou is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gns3-iou' has no installation candidate
```

Note: Bionic is shipped with libcrypto++6 but that provides libcrypto.so.6, not libcrypto.so.4.

**Comment by adosztal** [comment]
I checked the [PPA repo](https://launchpad.net/~gns3/+archive/ubuntu/ppa), gns3-iou is indeed missing for Bionic there.

**Comment by grossmj** [comment]
Ref https://gns3.com/qa/gns3-iou-not-working-on-ubuntu-1

**Comment by ziajka** [comment]
Hi @adosztal, gns3-iou should be on bionic now. Please let me know if it helped. Thanks!

**Comment by adosztal** [comment]
The shared library is there but it's still not found:
```
adosztal@lab:~/GNS3/images/IOU$ dpkg -l gns3-iou
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-================================================
ii  gns3-iou              0.0.1~bionic2   amd64           GNS3 support for IOU

adosztal@lab:~/GNS3/images/IOU$ dpkg -L gns3-iou
/.
/lib
/lib/i386-linux-gnu
/usr
/usr/share
/usr/share/doc
/usr/share/doc/gns3-iou
/usr/share/doc/gns3-iou/changelog.gz
/lib/i386-linux-gnu/libcrypto.so.4

adosztal@lab:~/GNS3/images/IOU$ ldd ./i86bi-linux-l3-adventerprisek9-15.4.1T.bin
	linux-gate.so.1 (0xf7f5b000)
	libcrypto.so.4 => not found
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7e34000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7e16000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7c3a000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7c35000)
	/lib/ld-linux.so.2 (0xf7f5d000)
```

**Comment by ziajka** [comment]
Hi @adosztal , have you tried `apt update` and then `apt install gns3-iou`? I just tried and everything should be fine. Please let me know if it help.

**Comment by adosztal** [comment]
Tried but it still doesn't work:
```
adosztal@lab:~$ sudo apt-get remove --purge gns3-iou
[sudo] password for adosztal: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  lib32z1 libc6-i386 libssl1.0.0:i386
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  gns3-iou*
0 upgraded, 0 newly installed, 1 to remove and 8 not upgraded.
After this operation, 10,2 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 203361 files and directories currently installed.)
Removing gns3-iou (0.0.1~bionic2) ...

adosztal@lab:~$ sudo apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  lib32z1 libc6-i386 libssl1.0.0:i386
0 upgraded, 0 newly installed, 3 to remove and 8 not upgraded.
After this operation, 15,8 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 203358 files and directories currently installed.)
Removing lib32z1 (1:1.2.11.dfsg-0ubuntu2) ...
Removing libc6-i386 (2.27-3ubuntu1) ...
Removing libssl1.0.0:i386 (1.0.2n-1ubuntu5) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

adosztal@lab:~$ sudo apt-get update
Hit:1 http://archive.canonical.com/ubuntu bionic InRelease                                                   
Hit:2 http://ppa.launchpad.net/ansible/ansible-2.5/ubuntu bionic InRelease                                   
Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease                                              
Hit:4 http://ppa.launchpad.net/gns3/ppa/ubuntu bionic InRelease                                              
Hit:5 https://packages.microsoft.com/repos/vscode stable InRelease                                           
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]                                  
Hit:7 http://ppa.launchpad.net/pmjdebruijn/darktable-release/ubuntu bionic InRelease                         
Get:8 https://deb.opera.com/opera-stable stable InRelease [2.592 B]                                          
Hit:9 http://hu.archive.ubuntu.com/ubuntu bionic InRelease                                                   
Get:10 http://hu.archive.ubuntu.com/ubuntu bionic-updates InRelease [83,2 kB]                                
Hit:11 http://prerelease.keybase.io/deb stable InRelease                                                     
Hit:12 http://hu.archive.ubuntu.com/ubuntu bionic-backports InRelease                                        
Hit:13 http://repository.spotify.com stable InRelease                                                      
Get:14 https://deb.opera.com/opera-stable stable/non-free amd64 Packages [1.804 B]   
Get:15 http://hu.archive.ubuntu.com/ubuntu bionic-updates/universe Sources [8.152 B]
Get:16 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main Sources [22,1 kB]
Get:17 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [61,8 kB]
Get:18 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [62,4 kB]
Get:19 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [22,5 kB]
Get:20 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [12,1 kB]
Get:21 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [8.506 B]           
Get:22 http://hu.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [13,1 kB]   
Get:23 http://hu.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [32,4 kB]     
Get:24 http://hu.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [32,4 kB]
Get:25 http://hu.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [16,1 kB]
Get:26 http://hu.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [5.728 B]
Get:27 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [204 B]    
Get:28 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [2.456 B]
Fetched 471 kB in 2s (233 kB/s)                
Reading package lists... Done

adosztal@lab:~$ sudo apt install gns3-iou
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  lib32z1 libc6-i386 libssl1.0.0:i386
The following NEW packages will be installed:
  gns3-iou lib32z1 libc6-i386 libssl1.0.0:i386
0 upgraded, 4 newly installed, 0 to remove and 17 not upgraded.
Need to get 3.622 kB/3.623 kB of archives.
After this operation, 15,8 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://hu.archive.ubuntu.com/ubuntu bionic/main i386 libssl1.0.0 i386 1.0.2n-1ubuntu5 [913 kB]
Get:2 http://hu.archive.ubuntu.com/ubuntu bionic/main amd64 libc6-i386 amd64 2.27-3ubuntu1 [2.651 kB]
Get:3 http://hu.archive.ubuntu.com/ubuntu bionic/main amd64 lib32z1 amd64 1:1.2.11.dfsg-0ubuntu2 [58,3 kB]
Fetched 3.622 kB in 1s (6.833 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libssl1.0.0:i386.
(Reading database ... 203032 files and directories currently installed.)
Preparing to unpack .../libssl1.0.0_1.0.2n-1ubuntu5_i386.deb ...
Unpacking libssl1.0.0:i386 (1.0.2n-1ubuntu5) ...
Selecting previously unselected package libc6-i386.
Preparing to unpack .../libc6-i386_2.27-3ubuntu1_amd64.deb ...
Unpacking libc6-i386 (2.27-3ubuntu1) ...
Replaced by files in installed package libc6:i386 (2.27-3ubuntu1) ...
Selecting previously unselected package lib32z1.
Preparing to unpack .../lib32z1_1%3a1.2.11.dfsg-0ubuntu2_amd64.deb ...
Unpacking lib32z1 (1:1.2.11.dfsg-0ubuntu2) ...
Selecting previously unselected package gns3-iou.
Preparing to unpack .../gns3-iou_0.0.1~bionic2_amd64.deb ...
Unpacking gns3-iou (0.0.1~bionic2) ...
Setting up libssl1.0.0:i386 (1.0.2n-1ubuntu5) ...
Setting up libc6-i386 (2.27-3ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up lib32z1 (1:1.2.11.dfsg-0ubuntu2) ...
Setting up gns3-iou (0.0.1~bionic2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

adosztal@lab:~$ cd GNS3/images/IOU/
adosztal@lab:~/GNS3/images/IOU$ ./i86bi-linux-l3-adventerprisek9-15.4.1T.bin 
./i86bi-linux-l3-adventerprisek9-15.4.1T.bin: error while loading shared libraries: libcrypto.so.4: cannot open shared object file: No such file or directory
```
The file was not found:
```
adosztal@lab:~/GNS3/images/IOU$ find / -type f -name libcrypto.so.4 2>/dev/null 
adosztal@lab:~/GNS3/images/IOU$ sudo find / -type f -name libcrypto.so.4 2>/dev/null 
adosztal@lab:~/GNS3/images/IOU$ 
```
Anyway it's fine if it works for everyone else but me; I don't use IOU for my daily labs. What about putting this on hold until someone else has the same issue?

**Comment by grossmj** [comment]
I confirm. I installed a fresh Ubuntu 18.04 in a VM and there is still an issue even after using `apt install gns3-iou`. Note that not all IOU images require the crypto library.

```
ldd ./i86bi_linux-adventerprisek9-ms.154-2.T4
	linux-gate.so.1 (0xf7f64000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7e47000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7e29000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7c4d000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7c48000)
	/lib/ld-linux.so.2 (0xf7f66000)
```

```
ldd ./i86bi-linux-l2-adventerprisek9-15.1a.bin 
	linux-gate.so.1 (0xf7fbf000)
	libcrypto.so.4 => not found
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7f85000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7e83000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7e65000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7c89000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7c84000)
	/lib/ld-linux.so.2 (0xf7fc1000)
```

**Comment by ehlers** [comment]
Just had a look into this issue and I'm amazed that this isn't diagnosed within one month.

@adosztal gave very good diagnostics: `ldd` shows, that libcrypto.so.4 isn't found, but `dpkg -L gns3-iou`shows, that it is installed. Using `ls -l /lib/i386-linux-gnu/libcrypto.so.4`shows, that this is a link to libcrypto.so.1, but this library doesn't exist in /lib/i386-linux-gnu.

Using https://packages.ubuntu.com/ informs us, that libcrypto.so.1 is included in libssl1.0.0:i386, which is also installed. **BUT** starting with bionic this library is installed in **/usr**/lib/i386-linux-gnu/, before it was /lib/i386-linux-gnu/.

So the issue is, that in bionic the symlink of libcrypto.so.4 links to a libcrypto.so.1 in a wrong directory.

**Comment by grossmj** [comment]
@ehlers do you have some experience making Debian packages? (.deb)

**Comment by ehlers** [comment]
No, sometimes/seldom I re-build a deb package, but I have never created one.

**Comment by grossmj** [comment]
@ziajka the simplest would be to update https://github.com/GNS3/gns3-build/blob/master/debian/gns3iou/links with the correct symlink but what about older versions of Ubuntu? How can we handle that?

**Comment by ehlers** [comment]
As I said, I have no real experience with building debs.

But I think, that the `links` file can be replaced by `postinst`/`postrm` scripts, see
https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.html#s-maintscripts

Then you are more flexible, something like the following could work for `postinst` (completely untested):
```
if [ -f /usr/lib/i386-linux-gnu/libcrypto.so.1 ]; then
        ln -s /usr/lib/i386-linux-gnu/libcrypto.so.1 /usr/lib/i386-linux-gnu/libcrypto.so.4
elif [ -f /lib/i386-linux-gnu/libcrypto.so.1 ]; then
        ln -s /lib/i386-linux-gnu/libcrypto.so.1 /lib/i386-linux-gnu/libcrypto.so.4
else
        echo "libcrypto.1 library not found" >&2
        exit 1
fi
```
Something similar should work for `postrm`.

**Comment by grossmj** [comment]
@ehlers thanks for the helpful input, I too have no experience with building debs. @noplay used to take care of this but it doesn't work on the project anymore :( Anyway, we will try with postinst / postrm.

**Comment by grossmj** [comment]
The package has been fixed. Thanks to everyone for the help!

**Comment by RyanBreaker** [comment]
I'm still experiencing this problem on fresh Ubuntu installs, `libcrypto.1 library not found`, or does the update have yet to propagate? This is after installing via the `remote-install.sh` script.

**Comment by grossmj** [comment]
Hi,

What Ubuntu version have you used?

**Comment by ehlers** [comment]
Partly it's my fault, in my above comment I used the incorrect filename  libcrypto.so.1, while libcrypto.so.1.0.0 is correct. That gives your error in Ubuntu 16.04.

Here the corrected version for postinst, tested both on 16.04 and 18.04 (the gns3-iou package for 14.04 hasn't changed):
```
#!/bin/sh

set -e

if [ -f /usr/lib/i386-linux-gnu/libcrypto.so.1.0.0 ]; then
    if [ ! -f /usr/lib/i386-linux-gnu/libcrypto.so.4 ]; then
        ln -s libcrypto.so.1.0.0 /usr/lib/i386-linux-gnu/libcrypto.so.4
    fi
elif [ -f /lib/i386-linux-gnu/libcrypto.so.1.0.0 ]; then
    if [ ! -f /lib/i386-linux-gnu/libcrypto.so.4 ]; then
        ln -s libcrypto.so.1.0.0 /lib/i386-linux-gnu/libcrypto.so.4
    fi
else
    echo "libcrypto.so.1.0.0 library not found" >&2
    exit 1
fi
```

What's still missing is a postrm script, which deletes the libcrypto.so.4 link during uninstallation.

**Comment by RyanBreaker** [comment]
@grossmj I've tried it so far on fresh installs of both Ubuntu Server 16.04 and 18.04.

**Comment by grossmj** [comment]
We have corrected the postinst script and added postrm.

Hopefully everything is good this time.

**Comment by RyanBreaker** [comment]
Ah yes, things are running fine for me now on 16.04. Thanks!

**Comment by adosztal** [comment]
Late confirmation. :) Works for me too.
