### ISSUE TITLE
500 error while creating mount source path

### ISSUE THREAD

**Issue by diepnghitinh** [GNS3/gns3-server#1590]
Help me, my error:
error while starting OpenvSwitch-2: Docker has returned an error: 500 error while creating mount source path '/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/docker/resources': mkdir /usr/share/gns3: read-only file system

**Comment by grossmj** [comment]
What version of GNS3 do you use?

**Comment by diepnghitinh** [comment]
I fixed that, remove docker and reinstall, thanks all.

**Comment by grossmj** [comment]
Thanks for the update.

**Comment by carlsaj** [comment]
I am having the same issue but reinstalling didn't fix my issue

**Comment by grossmj** [comment]
@carlsaj how have you installed GNS3? Do you get the exact following error message?

```
error while starting OpenvSwitch-1: Docker has returned an error: 500 error while creating mount source path '/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/docker/resources': mkdir /usr/share/gns3: read-only file system
```

**Comment by carlsaj** [comment]
I am using gns 2.2.5 and I followed the steps that are available on gns3 site and I am using Ubuntu 19 

The only difference is docker-ce doesn't exist on Ubuntu 19 I am installing docker and docker is working fine on its own 

Also the issue appears when I am using Ubuntu 19 because I have another PC which is running on Ubuntu 18.04 and it is working great

**Comment by gabrielestella** [comment]
I'm having the same issue.... the reinstall of Docker doesn't resolve that...
