### ISSUE TITLE
Export portable project forgets contents of "README"

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-server#1724]
This is only a minor annoyance, but I thought I would report it anyway.

When exporting a portable project, the previous contents of the `README.txt` don't seem to be used, instead the default "John Doe" contents are given:

![image](https://user-images.githubusercontent.com/44789/76142372-f6183880-6064-11ea-9b32-380f13ba925e.png)

It would be helpful if the existing README could be used as a default (of course, it can still be edited at this point)

**Comment by grossmj** [comment]
Done. Thanks :+1:

**Comment by candlerb** [comment]
I have tested this with 2.2.7, and I'm still seeing the same behaviour: exporting the running project gives me the "John Doe" message.

```
$ ls ~/GNS3/projects/17f0653f-71d2-46e4-8521-28cb40d5927d/
cndo.gns3  project-files  README.txt  snapshots
$ cat ~/GNS3/projects/17f0653f-71d2-46e4-8521-28cb40d5927d/README.txt
NSRC Campus Network Design and Operations - full GNS3 topology

6 campuses, each with 4 edge switches, 2 dist switches, 1 core, 1 border$
```

On export:

![image](https://user-images.githubusercontent.com/44789/79325368-f4b21980-7f08-11ea-8ad2-334b5ea0ca30.png)

Aha.  The [change](https://github.com/GNS3/gns3-gui/commit/5bb8b8e8bdf2fa9e2bf5dfd26081e5be5295ffa0) to the GUI tries to read the file from the local filesystem - but the server is running on a remote node!

I think instead the GUI should fetch `/v2/projects/<uuid>/files/README.txt` via the API.

```
$ curl xxxx:yyyy@192.168.122.1:3080/v2/projects/17f0653f-71d2-46e4-8521-28cb40d5927d/files/README.txt
NSRC Campus Network Design and Operations - full GNS3 topology

6 campuses, each with 4 edge switches, 2 dist switches, 1 core, 1 border
```

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-gui/commit/6787982408284c68fdcc7bf94470aef57223d7c5, thanks for thinking about this better solution! :+1:
