### ISSUE TITLE
[2.2.11] Multiple tests fail

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1796]
Ubuntu 20.04
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3

```
python3.8 setup.py install
sudo -u ${user} -EH py.test -vv
```
leads to
```
FAILED tests/test_config.py::test_reload - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_get_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmp5rn8pu_o',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',\n '-F',\n '-s',...
FAILED tests/handlers/api/compute/test_project.py::test_close_project[pyloop] - AssertionError: assert False
```
Full tests report
[gns3-server_2.2.11-20.04_amd64_tests.log](https://github.com/GNS3/gns3-server/files/4901847/gns3-server_2.2.11-20.04_amd64_tests.log)
.

**Comment by jean-christophe-manciot** [comment]
Debian bullseye
platform linux -- Python 3.8.4rc1, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3

```
python3.8 setup.py install
sudo -u ${user} -EH py.test -vv
```
leads to
```
FAILED tests/test_config.py::test_get_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_reload - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmpt833aacf',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\...
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start[pyloop] - AssertionError: assert ('/tmp/tmpt4g15wd6',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',...
```
Full tests report 
[gns3-server_2.2.11-11.0_amd64_tests.log](https://github.com/GNS3/gns3-server/files/4901865/gns3-server_2.2.11-11.0_amd64_tests.log)

.

**Comment by grossmj** [comment]
These tests should work now. Let me know if this isn't the case on your side. Thanks :+1:

**Comment by jean-christophe-manciot** [comment]
Actually, on debian bullseye (I haven't tested on Ubuntu focal yet), some still fail:
```
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
Using --randomly-seed=4151629570
rootdir: git-gns3-server, inifile: pytest.ini
plugins: aiohttp-0.3.0, timeout-1.4.1, cov-2.10.0, pythonpath-0.7.3, randomly-3.4.1, flaky-3.6.1
```
One important note: **qemu has been upgraded very recently to 1:5.0-13**.
```
FAILED tests/test_config.py::test_set_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_get_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_reload - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start[pyloop] - AssertionError: assert ('/tmp/tmp9phxo2u9',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',...
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmpn3wrjdwi',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\...
```
Full log
[gns3-server_2.2.11-11.0_amd64_tests.log](https://github.com/GNS3/gns3-server/files/5001329/gns3-server_2.2.11-11.0_amd64_tests.log)

**Comment by jean-christophe-manciot** [comment]
Different errors on Ubuntu focal with ```qemu 1:4.2-3ubuntu6.3```:
```
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
Using --randomly-seed=3567176611
rootdir: git-gns3-server, inifile: pytest.ini
plugins: aiohttp-0.3.0, timeout-1.4.1, pythonpath-0.7.3, randomly-3.4.1, flaky-3.6.1, cov-2.8.1
```
```
FAILED tests/handlers/api/compute/test_project.py::test_close_project[pyloop] - AssertionError: assert False
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmpc5lk70qk',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\...
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start[pyloop] - AssertionError: assert ('/tmp/tmp9lmip4id',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',...
FAILED tests/test_config.py::test_get_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_reload - RuntimeError: There is no current event loop in thread 'MainThread'.
FAILED tests/test_config.py::test_set_section_config - RuntimeError: There is no current event loop in thread 'MainThread'.
================================================== 7 failed, 874 passed, 141 warnings in 115.33s (0:01:55) ===================================================

Full log
[gns3-server_2.2.11-20.04_amd64_tests.log](https://github.com/GNS3/gns3-server/files/5009988/gns3-server_2.2.11-20.04_amd64_tests.log)
