### ISSUE TITLE
GNS3 Could not list VirtualBox VMs

### ISSUE THREAD

**Issue by alekho** [GNS3/gns3-server#2266]
Hello, when I try to turn on the virtual machine, I get the following error. 
```
Error while listing vms: GNS3VM: Could not list VirtualBox VMs: Can't access to VirtualBox API version:
{'API Version': '7_0', 'Minimum Guest RAM Size': '4 MB', 'Maximum Guest RAM Size': '2097152 MB', 'Minimum Video RAM Size': '0 MB', 'Maximum Video Size RAM': '256 Megabytes', 'Max Guest Monitors': '64', 'Minimum Guest CPUs': '1', 'Max Guest CPUs': '64', 'Virtual Disk Limit (Info)': '2199022206976 Bytes ', 'Maximum serial ports': '4', 'Maximum parallel ports': '2', 'Maximum boot position': '4', 'Maximum PIIX3 network adapters': '8', 'Maximum ICH9 network adapters': '36', 'Max PIIX3 IDE Controllers': '1', 'Max ICH9 IDE Controllers': '1', 'Max IDE Ports': '2', 'Max Devices per IDE Port': '2', 'Max PIIX3 SATA Controllers': '1', 'Maximum ICH9 SATA Controllers': '8', 'Maximum SATA ports': '30', 'Maximum devices per SATA port': '1', 'Maximum PIIX3 SCSI Controllers': ' 1', 'Max ICH9 SCSI Controllers': '8', 'Max SCSI Ports': '16', 'Max Devices per SCSI Port': '1', 'Max PIIX3 SAS Controllers': '1', 'Max ICH9 SAS Controllers': '8', 'Max SAS Ports': '255', 'Max Devices per SAS Port': '1', 'Max PIIX3 NVMe Controllers': '1', 'Max ICH9 NVMe Controllers': '8 ', 'Max NVMe ports': '255', 'Max devices per NVMe port': '1', 'Max PIIX3 virtio-scsi Controllers': '1', 'Max ICH9 virtio-scsi Controllers': '8', 'Max virtio-scsi ports': '256', 'Max devices per virtio-scsi port': '1', 'Max PIIX3 Floppy Controllers': '1', 'Max ICH9 Floppy Controllers': '1', 'Max Floppy Ports': '1', 'Max Devices Per Floppy Port': '2', 'Default Machine Folder': '/home/alekho/VirtualBox VMs', 'Raw Mode Supported': 'none', 'Exclusive use hardware virtualization': 'on', 'Default hard disk format': 'VDI', 'VRDE authentication library': 'VBoxAuth', 'Web service authentication library': 'VBoxAuth', 'Remote desktop extension package': ' ', ' VM encryption ExtPack': '', 'Log history size': '3', 'Default frontend': '', 'Default audio driver': 'PulseAudio', 'Autostart database path': ' ', 'Default Guest Additions ISO ': '/usr/lib/virtualbox/additions/VBoxGuestAdditions.iso', 'Log Level': 'all', 'Proxy Mode': 'System', 'Proxy URL': ' ', 'Custom language': 'ru_RU '}
```
Wherein
```console
vboxmanage list vms
"GNS3 VM" {1ee580f3-aec9-4c50-a399-28e93b488d71}
```
The doctor shows the following:
```
Checking if vmrun is installed...
WARNING The vmrun executable could not be found, VMware VMs cannot be used
```
I use Manjaro

**Comment by grossmj** [comment]
> Hello, when I try to turn on the virtual machine, I get the following error.

I have fixed the error.

> Checking if vmrun is installed...
WARNING The vmrun executable could not be found, VMware VMs cannot be used

vmrun is used for VMware, not VirtualBox.

**Comment by alekho** [comment]
> > Hello, when I try to turn on the virtual machine, I get the following error.
> 
> I have fixed the error.
> 
> > Checking if vmrun is installed...
> > WARNING The vmrun executable could not be found, VMware VMs cannot be used
> 
> vmrun is used for VMware, not VirtualBox.

Corrected this file in my system. According to your instructions. Unfortunately the problem remains

**Comment by grossmj** [comment]
What is the first line you see if you execute "vboxmanage list systemproperties"?

```
vboxmanage list systemproperties | grep API
API version:                     7_0
```

**Comment by alekho** [comment]
This command returns the same as yours

```
vboxmanage list systemproperties | grep API                                                                                                
Версия API:                     7_0

```

**Comment by grossmj** [comment]
Do you have a screenshot of the `Error while listing vms: GNS3VM: Could not list VirtualBox VMs: Can't access to VirtualBox API version` message please? I want to make sure the language settings of VirtualBox doesn't interfere with vboxmanage when executed by GNS3.

Thank you.

**Comment by grossmj** [comment]
@alekho ping?

**Comment by alekho** [comment]
Pong. I apologize for the long response.
![image](https://github.com/GNS3/gns3-server/assets/51817340/895f89b7-af3c-4efa-865b-968813118c82)

**Comment by grossmj** [comment]
Thanks for sharing this. I have raised the issue - on the VirtualBox forums: https://forums.virtualbox.org/viewtopic.php?t=110191

As suggested there, please could you try this command: `LANG=C VBoxManage list systemproperties` to see if the output is in English?

Thanks.

**Comment by alekho** [comment]
You command does not display anything, but if i write `LANG=En VBoxManage list systemproperties`, then the properties are displayed as expected.

```
 $ LANG=C VBoxManage list systemproperties                                                                                                    
 $ LANG=En VBoxManage list systemproperties                                                                                                  
API version:                     7_0
Minimum guest RAM size:          4 Megabytes
Maximum guest RAM size:          2097152 Megabytes
Minimum video RAM size:          0 Megabytes
Maximum video RAM size:          256 Megabytes
Maximum guest monitor count:     64
Minimum guest CPU count:         1
Maximum guest CPU count:         64
Virtual disk limit (info):       2199022206976 Bytes
Maximum Serial Port count:       4
Maximum Parallel Port count:     2
Maximum Boot Position:           4
Maximum PIIX3 Network Adapter count:   8
Maximum ICH9 Network Adapter count:   36
Maximum PIIX3 IDE Controllers:   1
Maximum ICH9 IDE Controllers:    1
Maximum IDE Port count:          2
Maximum Devices per IDE Port:    2
Maximum PIIX3 SATA Controllers:  1
Maximum ICH9 SATA Controllers:   8
Maximum SATA Port count:         30
Maximum Devices per SATA Port:   1
Maximum PIIX3 SCSI Controllers:  1
Maximum ICH9 SCSI Controllers:   8
Maximum SCSI Port count:         16
Maximum Devices per SCSI Port:   1
Maximum SAS PIIX3 Controllers:   1
Maximum SAS ICH9 Controllers:    8
Maximum SAS Port count:          255
Maximum Devices per SAS Port:    1
Maximum NVMe PIIX3 Controllers:  1
Maximum NVMe ICH9 Controllers:   8
Maximum NVMe Port count:         255
Maximum Devices per NVMe Port:   1
Maximum virtio-scsi PIIX3 Controllers:  1
Maximum virtio-scsi ICH9 Controllers:   8
Maximum virtio-scsi Port count:         256
Maximum Devices per virtio-scsi Port:   1
Maximum PIIX3 Floppy Controllers:1
Maximum ICH9 Floppy Controllers: 1
Maximum Floppy Port count:       1
Maximum Devices per Floppy Port: 2
Default machine folder:          /home/alekho/VirtualBox VMs
Raw-mode Supported:              no
Exclusive HW virtualization use: on
Default hard disk format:        VDI
VRDE auth library:               VBoxAuth
Webservice auth. library:        VBoxAuth
Remote desktop ExtPack:          
VM encryption ExtPack:           
Log history count:               3
Default frontend:                
Default audio driver:            PulseAudio
Autostart database path:         
Default Guest Additions ISO:     /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso
Logging Level:                   all
Proxy Mode:                      System
Proxy URL:                       
User language:                   C
```

**Comment by grossmj** [comment]
Thanks, I think we are making progress. Can you also post the content of `~/.config/VirtualBox`? Thanks 👍

**Comment by alekho** [comment]
Done =)
```
<?xml version="1.0"?>
<!--
** DO NOT EDIT THIS FILE.
** If you make changes to this file while any VirtualBox related application
** is running, your changes will be overwritten later, without taking effect.
** Use VBoxManage or the VirtualBox Manager GUI to make changes.
-->
<VirtualBox xmlns="http://www.virtualbox.org/" version="1.12-linux">
  <Global>
    <ExtraData>
      <ExtraDataItem name="GUI/LastItemSelected" value="m=1ee580f3-aec9-4c50-a399-28e93b488d71"/>
      <ExtraDataItem name="GUI/LastWindowPosition" value="410,159,1111,784"/>
      <ExtraDataItem name="GUI/Tools/LastItemsSelected" value="Extensions,Details"/>
    </ExtraData>
    <MachineRegistry>
      <MachineEntry uuid="{1ee580f3-aec9-4c50-a399-28e93b488d71}" src="/home/alekho/VirtualBox VMs/GNS3 VM/GNS3 VM.vbox"/>
    </MachineRegistry>
    <NetserviceRegistry>
      <DHCPServers>
        <DHCPServer networkName="HostInterfaceNetworking-vboxnet0" IPAddress="192.168.56.100" networkMask="255.255.255.0" lowerIP="192.168.56.101" upperIP="192.168.56.254" enabled="1"/>
      </DHCPServers>
    </NetserviceRegistry>
    <Updates enabled="false">
      <Host enabled="false" channel="1" checkFreqSec="86400" repoUrl="https://update.virtualbox.org" checkCount="0"/>
    </Updates>
    <SystemProperties defaultMachineFolder="/home/alekho/VirtualBox VMs" defaultHardDiskFormat="VDI" VRDEAuthLibrary="VBoxAuth" webServiceAuthLibrary="VBoxAuth" LogHistoryCount="3" proxyMode="0" exclusiveHwVirt="true"/>
    <USBDeviceFilters/>
  </Global>
</VirtualBox>

```

**Comment by grossmj** [comment]
One more test, please execute this command: `VBoxManage setproperty language C` then let me know if `VBoxManage list systemproperties` is in English. Thanks :)

**Comment by alekho** [comment]
Yep, in English. Now GNS3 work correct!!! Thanks!!!

**Comment by grossmj** [comment]
Great to hear and thanks for your help with this issue. I will probably add "VBoxManage setproperty language C" or set LANG=en when executing vboxmanage in GNS3.
