### ISSUE TITLE
Cannot connect to compute anymore GNS3 3.0.0 RC1

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-server#2411]
Describe the bug
After upgrading GNS3 to version 3.0.0RC1 I cannot load any existing topology created in earlier 3.0.0 versions.

GNS3 version and operating system (please complete the following information):

OS: ArchLinux
GNS3 version: 3.0.0 RC1
GNS3 server and GUI are running on same machine (bare metal)

To Reproduce

1. Start GNS3 systemd service. This completes successfully and I see the server is running
2. Start GNS3 client. I see on the GNS3 console that the authentication from GUI is successful.

```
POST http://127.0.0.1:8080/v3/access/users/authenticate
Authenticated with controller 127.0.0.1 on port 8080
GET http://127.0.0.1:8080/v3/templates
```

3. Try to open an existing project. The following warning message is shown: 
     `Cannot connect to compute 'ARCH-DESKTOP (controller)' with request POST /projects`

4. In the GNS3 server log I see these messages repeating multiple times

```
2024-08-13 10:55:09 INFO gns3server.controller.compute:370 Connecting to compute 'local'
2024-08-13 10:55:09 DEBUG gns3server.controller.compute:528 Attempting request to compute: GET ServerProtocol.http://127.0.0.1:8080/v3/compute/capabilities {'content-type': 'application/json'}
2024-08-13 10:55:09 WARNING gns3server.controller.compute:375 Cannot connect to compute 'local': serverprotocol.http://127.0.0.1:8080/v3/compute/capabilities
2024-08-13 10:55:11 DEBUG watchfiles.main:265 rust notify timeout, continuing
```

**Comment by grossmj** [comment]
Please can you let me know what version of aiohttp is installed? thanks.

**Comment by cristian-ciobanu** [comment]
I have aiohttp version 3.10.3 installed.

**Comment by grossmj** [comment]
Please try to downgrade to version 3.9.5.

This is what we have in the requirements.txt file:

aiohttp>=3.9.5,<3.10

Thanks.

**Comment by cristian-ciobanu** [comment]
I have downgraded back to 3.9.5 and now the projects load fine. 
Thanks for pointing me in the right direction.

**Comment by grossmj** [comment]
We need to add support for the latest aiohttp

**Comment by cristian-ciobanu** [comment]
Hello @grossmj 

I have updated GNS3 3.0.0 to the latest git release and I cannot connect anymore again. In the GNS3 GUI in the servers summary it is shown as grayed not green as normal.
Also in the exception log I see this traceback message popping up constantly

`=== GNS3 3.0.0rc1 traceback on 06 nov 2024 16:42:43 ===
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/gns3/qt/__init__.py", line 179, in partial
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gns3/http_client.py", line 477, in _dataReadySlot
    if context["query_id"] in self._buffer:
       ~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
`
Environment:
OS: ArchLinux
GNS3 version: 3.0.0 (latest commit)
Python version 3.12
AioHTTP: 3.10.5 (also tried 3.10.10)
GNS3 server and GUI are running on same machine (bare metal)

**Comment by cristian-ciobanu** [comment]
As a side note, previously I used GNS3 3.0.0 RC1 with Aiohttp 3.9.5 and it worked fine so I assume something changed in between.

**Comment by grossmj** [comment]
Not sure what is wrong with the GUI, I don't think it is because of the aiohttp version. I pushed a fix, hopefully this solves the problem on your side.

**Comment by cristian-ciobanu** [comment]
I compiled the latest version and it is still the same but the exception thrown is a little bit different
`****** Exception detected, traceback information saved in /home/cioby/.config/GNS3/3.0/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/gns3/qt/__init__.py", line 179, in partial
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gns3/http_client.py", line 477, in _dataReadySlot
    if "query_id" in context and context["query_id"] in self._buffer:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

**Comment by grossmj** [comment]
I think I fixed the problem this time. Please give it a try on your side. Thanks :)

**Comment by cristian-ciobanu** [comment]
I Just compiled the latest 3.0 branch from git and indeed it fixes the issue. After starting the GUI client it connects successfully with the server and I do not see anymore the exception in the logs.
@grossmj thanks for fixing this issue.
