### ISSUE TITLE
Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by molaeiali** [GNS3/gns3-server#806]
Getting 
`Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused`
after installing it from AUR

```
~$ uname -a
Linux host 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux
```

```
~$ pacman -Qi gns3-server 
Name            : gns3-server
Version         : 1.5.1-1
Description     : GNS3 network simulator. Server package.
Architecture    : any
URL             : https://github.com/GNS3/gns3-server
Licenses        : GPL3
Groups          : gns3
Provides        : None
Depends On      : python-jsonschema  python-aiohttp  python-jinja  python-raven  python-psutil  python-zipstream
Optional Deps   : dynamips: Cisco router emulator.
                  vboxwrapper: VirtualBox wrapper for GNS3.
                  iouyap: Bridge IOU to UDP, TAP and Ethernet.
                  qemu: Used by GNS3 to run Cisco ASA, PIX and IDS. [installed]
                  vpcs: Simple PC emulation for basic network operations.
                  ubridge: Bridge for UDP tunnels, Ethernet, TAP and VMnet interfaces.
                  gns3-gui: graphical user interface for GNS3 server. [installed]
Required By     : None
Optional For    : gns3-gui
Conflicts With  : None
Replaces        : None
Installed Size  : 3.50 MiB
Packager        : Unknown Packager
Build Date      : Mon 05 Dec 2016 12:02:57 AM IRST
Install Date    : Mon 05 Dec 2016 12:03:00 AM IRST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**Comment by noplay** [comment]
What display:
'''
Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused
'''

The GNS3 gui or it's something you see in the server console?

**Comment by molaeiali** [comment]
I get it from GNS3 GUl, first a window pops up saying connecting to local server and then an other popup with error message

**Comment by noplay** [comment]
If you start the server by hand before does it work?

```
# gns3server
```

**Comment by cioby23** [comment]
This issue has been fixed in version 1.5.2. You need to upgrade. I see you are using the version provided in ArchLinux AUR which is outdated.

**Comment by suhasjanardhan** [comment]
I have similar problem where it says Could not connect to 192.168.56.1 on port 3080: [Errno 111] Connection refused. I'm using the latest version 2.0.2

**Comment by jalalsfs** [comment]
I am using Fedora 26 with gns3-gui-2.0.3-3, and the same issue here, I opened 3080/tcp port, but that doesn't fix the problem, what I get when I run gns3server from the terminal is:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 971, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 862, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (yarl 0.12.0 (/usr/lib64/python3.6/site-packages), Requirement.parse('yarl<0.10,>=0.9.8'), {'gns3-server'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gns3server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3038, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3051, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 672, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 857, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'yarl<0.10,>=0.9.8' distribution was not found and is required by gns3-server

**Comment by grossmj** [comment]
Make sure you reinstall the gns3-server package.

**Comment by hezekiahc** [comment]
I am encountering the same issue as jalalsfs. I am running openSUSE Tumbleweedm with yarl 0.11, and GNS3 server 2.0.3-1.1. I've reinstalled GNS3 server, and there has been no change:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, i
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, i
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, i
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (yarl 0.13.0 (/usr/lib64/python3.6/siteuirement.parse('yarl<0.10,>=0.9.8'), {'gns3-server'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gns3server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3142, 
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, 
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3155, master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, i
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, iequirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, i
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'yarl<0.10,>=0.9.8' distribution was notequired by gns3-server

**Comment by hezekiahc** [comment]
I was able to solve the issue. I had to run the following command to install the proper version of yarl: **sudo pip3 install -U yarl==0.9.8** Once I did that, I had to install the proper version of aiohttp-cors with a similar command, and the server started up.

**Comment by nex0ma** [comment]
opensuse tumbleweed
Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
pip3 install -U yarl==0.9.8
pip3 install -U aiohttp-cors==0.5.1


 # gns3server 
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.0.3', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.6/site-packages/gns3server/main.py", line 78, in main
    from gns3server.run import run
  File "/usr/lib/python3.6/site-packages/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.6/site-packages/gns3server/web/web_server.py", line 25, in <module>
    import asyncio
  File "/usr/lib/python3.6/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.6/site-packages/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax

**Comment by ihwanmuslim** [comment]
Moreover, you can install GNS3 very easily with the github release version 2.2.14. Install gns3-gui and gns3-server. Extract both, then type in the terminal "python setup.py install", and of course make sure it is in the gns3 directory. Don't forget to check the dependency or what files are needed.

**Comment by sandipg0071** [comment]
I have installed GNS3 on RHEL 9. but while stating gns3 its throwing an error.
"Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused"
